// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FileDetail: typeof import('./src/components/VFile/FileDetail.vue')['default']
    FileRead: typeof import('./src/components/VFile/FileRead.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCard: typeof import('./src/components/VCard.vue')['default']
    VDeveloper: typeof import('./src/components/VDeveloper.vue')['default']
    VHeader: typeof import('./src/components/VContainer/VHeader.vue')['default']
    VLottie: typeof import('./src/components/VLottie.vue')['default']
    VMain: typeof import('./src/components/VContainer/VMain.vue')['default']
    VRadio: typeof import('./src/components/VRadio.vue')['default']
    VscreenTip: typeof import('./src/components/VscreenTip.vue')['default']
    VSwitchType: typeof import('./src/components/VSwitchType.vue')['default']
  }
}
